// @ts-check
import { defineConfig } from 'astro/config';

import { SITE_URL, LOCALES, DEFAULT_LOCALE } from './src/data/site-constants.mjs';

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,
  trailingSlash: 'always',

  i18n: {
    defaultLocale: DEFAULT_LOCALE,
    locales: [...LOCALES],
    routing: {
      // English lives at the root (/), other languages at /de/, /es/, ...
      prefixDefaultLocale: false,
      redirectToDefaultLocale: false,
    },
  },

  // Sitemap is generated by src/pages/sitemap.xml.ts rather than by
  // @astrojs/sitemap, so that hreflang alternates reflect which
  // translations actually exist. See that file for the reasoning.
  integrations: [],

  build: {
    // One stylesheet beats a waterfall of tiny ones on mobile connections.
    inlineStylesheets: 'auto',
    format: 'directory',
  },

  image: {
    // Cloudflare Pages serves the prebuilt files; all optimisation happens at build time.
    responsiveStyles: true,
    layout: 'constrained',
  },

  vite: {
    build: {
      cssMinify: 'lightningcss',
    },
  },
});
