/**
 * Downloads the webfonts from Google Fonts into public/fonts/ and writes a
 * local @font-face stylesheet.
 *
 * Run once (or after changing FAMILIES); the results are committed, so the
 * built site never makes a request to a Google server. That is a real
 * performance win and it keeps the site free of third-party requests, which
 * matters for a business operating under GDPR.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'styles', 'fonts.css');

// Only these subsets are shipped. latin + latin-ext together cover English,
// German, Spanish, Catalan, Dutch and French — every language on the site.
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Fraunces:opsz,wght@9..144,400;9..144,600' +
  '&family=Inter:wght@400;500;600' +
  '&display=swap';

// Google only serves woff2 to browsers that advertise support for it.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36';

const res = await fetch(CSS_URL, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`Google Fonts returned ${res.status}`);
const css = await res.text();

await mkdir(OUT_DIR, { recursive: true });

// Each @font-face is preceded by a `/* subset */` comment.
const blocks = css.split('/*').slice(1);

// Both families are served as variable fonts: several requested weights map to
// one file. Group by that file so each ends up as a single @font-face with a
// weight *range*, which is how a variable font is meant to be declared.
const faces = new Map(); // remote url -> { family, style, subset, range, weights:Set }

for (const raw of blocks) {
  const subset = raw.slice(0, raw.indexOf('*/')).trim();
  if (!KEEP_SUBSETS.has(subset)) continue;

  const block = raw.slice(raw.indexOf('*/') + 2);

  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([\d\s]+);/.exec(block)?.[1].trim();
  const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1].trim();
  if (!family || !url || !weight) continue;

  const face = faces.get(url) ?? { family, style, subset, range, weights: new Set() };
  // A block may already carry a range like "400 600"; take every number in it.
  for (const w of weight.split(/\s+/)) face.weights.add(Number(w));
  faces.set(url, face);
}

const out = [
  '/* Self-hosted webfonts. Generated by scripts/fetch-fonts.mjs — do not edit by hand. */',
];

for (const [url, face] of faces) {
  const file = `${face.family.toLowerCase()}-${face.subset}.woff2`;

  const font = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!font.ok) throw new Error(`Failed to download ${url}: ${font.status}`);
  const bytes = Buffer.from(await font.arrayBuffer());
  await writeFile(path.join(OUT_DIR, file), bytes);
  console.log(`  ↓ ${file} (${(bytes.length / 1024).toFixed(0)} KB)`);

  const weights = [...face.weights].sort((a, b) => a - b);
  const weightValue =
    weights.length > 1 ? `${weights[0]} ${weights[weights.length - 1]}` : String(weights[0]);

  out.push(
    '',
    '@font-face {',
    `  font-family: '${face.family}';`,
    `  font-style: ${face.style};`,
    `  font-weight: ${weightValue};`,
    '  font-display: swap;',
    `  src: url('/fonts/${file}') format('woff2');`,
    ...(face.range ? [`  unicode-range: ${face.range};`] : []),
    '}'
  );
}

await mkdir(path.dirname(CSS_OUT), { recursive: true });
await writeFile(CSS_OUT, out.join('\n') + '\n');

console.log(`\nWrote ${faces.size} font files and ${path.relative(ROOT, CSS_OUT)}`);
